/* eslint-disable @next/next/no-img-element */
import Head from 'next/head';
export default function Home() {
  return (
    <>
      <Head>
        <title>Meeting</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="meeting-screen container-fluid">
        <div className="row" style={{ height: '100vh' }}>
          <div className="left col-md-4 ">
            <div className="logo">
              <img src="/moclogo.png" alt="moclogo" />
            </div>
          </div>
          <div className="right col-md-8">
            <div className="right-detail">
              <div className="des">
                <div className='p-3'>
                  <img src="/moclogo.png" alt="moclogo" />
                  <h1>Coming soong</h1>
                  <h4>Are you ready?</h4>
                  <p>
                    Ever wanted to impresgs your audience at first view? Use
                    this unique and beautiful website template.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
